import en from './en.js'

// Keep English as a fallback for newly added strings until they are translated.
const id = {
  ...en,
  inbox: 'Kotak Masuk', drafts: 'Draf', sent: 'Terkirim', starred: 'Berbintang', settings: 'Pengaturan', analytics: 'Analitik', allUsers: 'Semua Pengguna', allMail: 'Semua Email', permissions: 'Peran', inviteCode: 'Kode Undangan', SystemSettings: 'Pengaturan Sistem',
  noMoreData: 'Tidak ada data lagi', noMessagesFound: 'Tidak ada email ditemukan', addAccount: 'Tambah Alamat Email', account: 'Alamat', userAccount: 'Alamat Email Pengguna', deleteUser: 'Hapus Akun', deleteUserBtn: 'Hapus',
  changePassword: 'Ubah Kata Sandi', newPassword: 'Kata sandi baru', confirmPassword: 'Konfirmasi kata sandi', add: 'Tambah', manage: 'Kelola', rename: 'Ganti nama', delete: 'Hapus', save: 'Simpan', profile: 'Profil', change: 'Ubah', changePwdBtn: 'Ubah', username: 'Nama pengguna', password: 'Kata sandi', setForwarding: 'Atur Penerusan', forwardingEmailDesc: 'Teruskan email masuk untuk alamat ini ke satu Gmail pemilik. Alamat Gmail harus sudah diverifikasi di Cloudflare.', forwardingEmailPlaceholder: 'nama{\'@\'}gmail.com', accountForwarding: 'Penerusan per Alamat', accountForwardingDesc: 'Pilih alamat email, lalu atur Gmail penerimanya di sini.',
  delAccount: 'Hapus Akun', delAccountMsg: 'Akun dan data Anda akan dihapus permanen dan tidak dapat dipulihkan', totalReceived: 'Total Diterima', totalSent: 'Total Terkirim', totalMailboxes: 'Total Alamat Email', totalUsers: 'Total Pengguna', deleted: 'Dihapus', selectDeleted: 'Dihapus', active: 'Aktif',
  emailSource: 'Sumber Email', userGrowth: 'Pertumbuhan Pengguna', emailGrowth: 'Pertumbuhan Email', emailSent: 'Terkirim', emailReceived: 'Diterima', sentToday: 'Terkirim Hari Ini', total: 'Total', growthTotalUsers: 'Total Pengguna', searchByEmail: 'Masukkan email untuk mencari', searchMail: 'Cari email',
  tabReceived: 'Diterima', tabSent: 'Terkirim', tabMailboxes: 'Alamat', tabRegisteredAt: 'Terdaftar pada', tabStatus: 'Status', tabRole: 'Peran', roleName: 'Nama', role: 'Nama', all: 'Semua', normal: 'Normal', banned: 'Diblokir', reset: 'Atur ulang', restore: 'Pulihkan', deletePermanently: 'Hapus Permanen', delPermanentlyConfirm: 'Hapus permanen {msg}? Email ini akan langsung bisa dipakai lagi, tapi tindakan ini tidak bisa dibatalkan.', tabSetting: 'Pengaturan',
  registrationIp: 'IP Pendaftaran', recentIP: 'IP Terbaru', recentActivity: 'Aktivitas Terbaru', loginDevice: 'Perangkat Masuk', loginSystem: 'Sistem Masuk', browserLogin: 'Browser Masuk', unauthorized: 'Tidak berwenang', unlimited: 'Tanpa batas', sendCount: 'Kirim email: ', accountCount: 'Tambah alamat: ', action: 'Tindakan', chgPwd: 'Kata sandi', perm: 'Peran', btnBan: 'Blokir', admin: 'Admin', addUser: 'Tambah Pengguna', select: 'Pilih', unknown: 'Tidak diketahui', changePerm: 'Ubah Peran',
  from: 'Dari', subject: 'Subjek', sender: 'Pengirim', user: 'Pengguna', searchByContent: 'Masukkan teks untuk mencari', noRecipient: 'Tanpa penerima', received: 'Diterima', selectEmail: 'Email', order: 'Urutan', default: 'Bawaan', description: 'Deskripsi', expand: 'Perluas', collapse: 'Ciutkan', daily: 'Harian', internal: 'Internal',
  searchRegKeyDesc: 'Masukkan kode undangan untuk mencari', remainingUses: 'Sisa Penggunaan', exhausted: 'Habis', validUntil: 'Berlaku hingga', expired: 'Kedaluwarsa', copy: 'Salin', copyCode: 'Salin Kode', codeLabel: 'Kode: ', history: 'Riwayat', addRegKey: 'Tambah Kode Undangan', regKey: 'Kode Undangan', noCodeFound: 'Tidak ada email ditemukan', useHistory: 'Riwayat Penggunaan', date: 'Tanggal', roleDesc: 'Peran', noSubject: 'Tanpa subjek', recipient: 'Kepada', delivered: 'Terkirim', complained: 'Dikeluhkan', delayed: 'Tertunda', bounced: 'Terpental', attachments: 'Lampiran', attCount: 'Total {total}', emailCount: 'Total {total}', home: 'Beranda',
  loginBtn: 'Masuk', regBtn: 'Daftar', loginTitle: 'Masuk ke akun Anda untuk mengakses email', regTitle: 'Daftar akun untuk menggunakan email', confirmPwd: 'Konfirmasi kata sandi', regKeyOptional: 'Kode undangan (opsional)', noAccount: 'Belum punya akun? ', hasAccount: 'Sudah punya akun? ', regSwitch: 'Daftar', loginSwitch: 'Masuk',
  websiteSetting: 'Situs web', websiteReg: 'Pendaftaran', loginDomain: 'Sembunyikan Domain Masuk', multipleEmail: 'Beberapa Alamat Email', multipleEmailDesc: 'Izinkan pengguna menambahkan beberapa alamat email', customization: 'Kustomisasi', websiteTitle: 'Judul', loginBoxOpacity: 'Opasitas Kotak Masuk', loginBackground: 'Latar Belakang', emailSetting: 'Email', receiveEmail: 'Terima Email', autoRefresh: 'Muat Ulang Otomatis', autoRefreshDesc: 'Ambil email terbaru dari server secara otomatis', sendEmail: 'Kirim Email', resendToken: 'Token Resend', cloudflareEmailSending: 'Pengiriman Email Cloudflare', blackList: 'Daftar Blokir',
  codeRecognition: 'Pengenalan Kode Verifikasi', codeRecognitionRules: 'Aturan Pengenalan', codeRecognitionRulesDesc: 'Hanya kenali email yang memuat informasi berikut. Kosong berarti semua.', oss: 'Penyimpanan Objek', osDomain: 'Domain', ossDomainDesc: 'Kosongkan bila memakai penyimpanan KV.', emailPush: 'Notifikasi Email', tgBot: 'Bot Telegram', disable: 'Nonaktifkan', disabled: 'Dinonaktifkan', otherEmail: 'Teruskan ke Email Eksternal', forwardingRules: 'Aturan Penerusan', forwardAll: 'Semua', rules: 'Aturan', turnstileSetting: 'Turnstile', signUpVerification: 'Verifikasi Pendaftaran', addEmailVerification: 'Verifikasi Tambah Email', about: 'Tentang', version: 'Versi', community: 'Komunitas',
  changeTitle: 'Ubah Judul', addResendTokenDesc: 'Masukkan untuk menambah; kosongkan untuk menghapus', addOsDomain: 'Tambah Domain', domainDesc: 'Domain', addTurnstileSecret: 'Tambah secret Turnstile', backgroundTitle: 'Ubah Latar Belakang', tgBotDesc: 'Teruskan email yang diterima ke bot Telegram', tgBotToken: 'Token bot', toBotTokenDesc: 'Beberapa chat_id pengguna, pisahkan dengan koma', otherEmailDesc: 'Email dapat diteruskan ke email eksternal, tetapi harus diverifikasi di Cloudflare', otherEmailInputDesc: 'Pisahkan beberapa alamat email dengan koma', forwardingRulesDesc: 'Penerusan berbasis aturan hanya meneruskan email yang diterima oleh alamat tertentu', ruleEmailsInputDesc: 'Pisahkan beberapa alamat email dengan koma', resendTokenList: 'Daftar Token', domain: 'Domain', optional: 'Opsional', subjectInputDesc: 'Masukkan subjek email', changeUserName: 'Ubah Nama Pengguna',
  send: 'Kirim', reply: 'Balas', forward: 'Teruskan', confirm: 'Konfirmasi', cancel: 'Batal', close: 'Tutup', delEmailConfirm: 'Hapus email ini?', delSuccessMsg: 'Berhasil dihapus', emptyEmailMsg: 'Email tidak boleh kosong', notEmailMsg: 'Email tidak valid', minEmailPrefix: 'Email minimal {msg} karakter', emptyPwdMsg: 'Kata sandi tidak boleh kosong', pwdLengthMsg: 'Kata sandi minimal 6 karakter', confirmPwdFailMsg: 'Kedua kata sandi tidak sama', emptyRegKeyMsg: 'Kode undangan tidak boleh kosong', regSuccessMsg: 'Pendaftaran berhasil', copySuccessMsg: 'Berhasil disalin', copyFailMsg: 'Gagal menyalin', clearRegKey: 'Hapus semua kode undangan yang tidak valid?', clearSuccess: 'Berhasil dibersihkan', emptyRole: 'Peran tidak boleh kosong', emptyTimeMsg: 'Waktu berlaku hingga tidak boleh kosong', emptyCountMsg: 'Jumlah tersedia tidak boleh kosong', addSuccessMsg: 'Berhasil ditambahkan', delConfirm: 'Hapus {msg}?', delUsersConfirm: 'Hapus pengguna yang dipilih?', emptyRoleNameMsg: 'Nama peran tidak boleh kosong', saveSuccessMsg: 'Berhasil disimpan',
  changeRoleTitle: 'Ubah Peran', addRoleTitle: 'Tambah Peran', emptyUserNameMsg: 'Nama tidak boleh kosong', delAccountConfirm: 'Hapus akun saat ini beserta semua data terkait?', clearAllDelConfirm: 'Tindakan ini tidak dapat dibatalkan. Ketik <b style="font-weight: bold">DELETE</b> untuk melanjutkan', warning: 'Peringatan', inputErrorMessage: 'Ketik DELETE untuk mengonfirmasi', delBackgroundConfirm: 'Hapus latar belakang ini?', enable: 'Aktifkan', enabled: 'Diaktifkan', reSendConfirm: 'Atur ulang jumlah pengiriman {msg}?', reSuccessMsg: 'Berhasil diatur ulang', restoreConfirm: 'Pulihkan {msg}?', normalRestore: 'Pemulihan normal', allRestore: 'Termasuk data yang dihapus', restoreSuccessMsg: 'Berhasil dipulihkan', banRestore: 'Blokir {msg}?', logOut: 'Keluar', clearContentConfirm: 'Hapus semua konten?', emptyRecipientMsg: 'Email penerima tidak boleh kosong', emptySubjectMsg: 'Subjek tidak boleh kosong', emptyContentMsg: 'Isi email tidak boleh kosong', noSeparateSendMsg: 'Pengiriman terpisah belum mendukung lampiran', sendSuccessMsg: 'Berhasil dikirim', sendFailMsg: 'Gagal mengirim', saveDraftConfirm: 'Simpan draf?', delEmailsConfirm: 'Hapus email yang dipilih?', delOneEmailConfirm: 'Hapus email ini?', sending: 'Mengirim email...', sendingErrorMsg: 'Pengiriman sedang berlangsung', networkErrorMsg: 'Kesalahan jaringan. Periksa koneksi internet Anda', timeoutErrorMsg: 'Waktu habis. Coba lagi nanti', serverBusyErrorMsg: 'Server sibuk. Coba lagi nanti', reqFailErrorMsg: 'Permintaan gagal. Coba lagi nanti', message: 'Pesan', language: 'Bahasa', sendBanned: 'Diblokir', sendInternal: 'Hanya internal', wrote: 'menulis', support: 'Dukungan',
  supportDesc: 'Traktir saya teh', featDesc: 'Deskripsi Fitur', emailInterception: 'Pencegatan Email', emailInterceptionDesc: 'Masukkan domain atau alamat email untuk mencegah pengguna menerima email dari situs tertentu (masukkan * untuk memblokir semua)', availableDomains: 'Domain Tersedia', availableDomainsDesc: 'Batasi pengguna ke domain email tertentu. Domain yang tidak ada dalam daftar akan diblokir saat pendaftaran, penambahan alamat, serta pengiriman/penerimaan email. Jika kosong, semua domain diizinkan.', backgroundUrlDesc: 'URL gambar', localUpload: 'Unggah lokal', imageLink: 'URL gambar', imageLinkErrorMsg: 'URL gambar tidak valid', backgroundWarning: 'Ukuran berkas gambar memengaruhi kecepatan muat situs', rulesVerify: 'Aturan', rulesVerifyTitle: 'Picu Setelah {count} Penggunaan Harian per IP', botVerifyMsg: 'Harap verifikasi bahwa Anda manusia', noticeTitle: 'Pengumuman', noticePopup: 'Pop-up Masuk', icon: 'Ikon', position: 'Posisi', offset: 'Offset', duration: 'Durasi', topRight: 'Kanan Atas', topLeft: 'Kiri Atas', bottomRight: 'Kanan Bawah', bottomLeft: 'Kiri Bawah', width: 'Lebar', titleDesc: 'Judul', noticeContentDesc: 'Isi pengumuman mendukung HTML', verifyModuleFailed: 'Modul verifikasi gagal dimuat. Segarkan halaman', popUp: 'Pop-up', noRecipientTitle: 'Tanpa Penerima', noRecipientDesc: 'Email dapat diterima meskipun alamat email belum terdaftar', preview: 'Pratinjau', help: 'Bantuan', document: 'Dokumen', clearEmail: 'Pembersihan Email', sendEmailAddress: 'Email Pengirim', toEmail: 'Kepada Email', equal: 'Sama dengan', leading: 'Awalan', to: 'Kepada', clear: 'Bersihkan', include: 'Mencakup', delAllConfirm: 'Yakin ingin menghapusnya?', pin: 'Sematkan', s3Configuration: 'Konfigurasi S3', confirmDeletionOfContacts: 'Hapus kontak?', recentContacts: 'Kontak terbaru', selectContacts: 'Pilih', forcePathStyleDesc: 'Beberapa penyimpanan objek mandiri memerlukan akses gaya path', storageType: 'Lokasi Penyimpanan', customDomainDesc: 'Domain khusus Worker', show: 'Tampilkan', hide: 'Sembunyikan', onlyName: 'Hanya nama', emailText: 'Teks Email', emailPrefix: 'Awalan Email', atLeast: 'Minimal', mustNotContain: 'Tidak boleh memuat', mustNotContainDesc: 'Pisahkan dengan koma', blackSubjectDesc: 'Subjek', blackContentDesc: 'Isi', blackFromDesc: 'Pengirim atau domain', senderRules: 'Alamat atau domain pengirim', blackListDesc: 'Tolak email yang memuat informasi berikut', setSuccess: 'Pengaturan berhasil disimpan', details: 'Detail', userDetails: 'Detail Pengguna', markAsRead: 'Tandai Sudah Dibaca', star: 'Beri Bintang', setRole: 'Atur Peran', adminDeleteUser: 'Hapus Pengguna', banUser: 'Blokir Pengguna', enableUser: 'Aktifkan Pengguna', restoreUser: 'Pulihkan Pengguna', searchUser: 'Cari berdasarkan pengguna', searchEmail: 'Cari berdasarkan Email', searchSender: 'Cari berdasarkan pengirim', userEmail: 'Alamat Email'
}

id.helpBubbleText = 'Butuh bantuan memakai Cloud Mail?'
id.helpCenter = 'Kunjungi khwarizmi.co.id'
id.emailAdmin = 'Email admin'

export default id
